version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - next
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  verbosity: normal
artifacts:
- path: bin\$(configuration)\*
  name: Full Build
deploy:
- provider: GitHub
  description: I am testing automated releases using AppVeyor
  auth_token:
    secure: 1Dzj/ZfH3EBVsuVHw0Ez/zNxIql3G8gwr9iaO2Z1Q1IeH3xHRPzGmBQljDgsdyLL
  artifact: Full Build
notifications:
- provider: Email
  to:
  - akauffman@cet.aero
  subject: Hooray! AppVeyor for AccessQueryEditor
  message: Build success
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - akauffman@cet.aero
  subject: Boo! AppVeyor for AccessQueryEditor
  message: Build failure
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false